// Code generated by protoc-gen-go.
// source: header.proto
// DO NOT EDIT!

/*
Package header is a generated protocol buffer package.

It is generated from these files:
	header.proto

It has these top-level messages:
	DSROptions
	FloodingOptions
	Header
*/
package header

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DSROptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DSROptions) Reset()         { *m = DSROptions{} }
func (m *DSROptions) String() string { return proto.CompactTextString(m) }
func (*DSROptions) ProtoMessage()    {}

type FloodingOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FloodingOptions) Reset()         { *m = FloodingOptions{} }
func (m *FloodingOptions) String() string { return proto.CompactTextString(m) }
func (*FloodingOptions) ProtoMessage()    {}

type Header struct {
	DsrOptions       *DSROptions      `protobuf:"bytes,2,opt,name=dsr_options" json:"dsr_options,omitempty"`
	FloodingOptions  *FloodingOptions `protobuf:"bytes,3,opt,name=flooding_options" json:"flooding_options,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}

func (m *Header) GetDsrOptions() *DSROptions {
	if m != nil {
		return m.DsrOptions
	}
	return nil
}

func (m *Header) GetFloodingOptions() *FloodingOptions {
	if m != nil {
		return m.FloodingOptions
	}
	return nil
}

type Header_RouteRequest struct {
	Destination      *string `protobuf:"bytes,1,req,name=destination" json:"destination,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Header_RouteRequest) Reset()         { *m = Header_RouteRequest{} }
func (m *Header_RouteRequest) String() string { return proto.CompactTextString(m) }
func (*Header_RouteRequest) ProtoMessage()    {}

func (m *Header_RouteRequest) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func init() {
}
